server:
  port: 8000
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    username: admin
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect